# The official image of the node
FROM node:boron

ARG VERSION=1.0.0

# Create app directory
WORKDIR /usr/src/app

# Set required environment variables
ENV NODE_ENV production

# Install app dependencies
COPY package.json .
# For npm@5 or later, copy package-lock.json as well
# COPY package.json package-lock.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]
